services:
  web:
    image: nginx:alpine
    container_name: pi-dashboard
    volumes:
      - ./dist/:/usr/share/nginx/dashboard:ro
      - /home/mb/minecraft/plugins/Pl3xMap/web:/usr/share/nginx/mc-map:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    # depends_on:
    #   - api
    restart: unless-stopped
  # api:
  #   image: node:alpine
  #   container_name: pi-dashboard-api
  #   volumes:
  #     - ./:/app
  #     - /home/mb/minecraft/:/minecraft
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   command: sh -c "cd app && npm install && npm run server"
