networks:
  proxy:
    name: proxy
    external: true

services:
  web:
    image: nginx:alpine
    container_name: dashboard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./dist/:/usr/share/nginx/dashboard:ro
      - /home/mbacalan/games/minecraft/plugins/Pl3xMap/web:/usr/share/nginx/mc-map:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "85:80"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`home.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"

  api:
    build: .
    container_name: dashboard-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/mbacalan/games/minecraft:/app/minecraft
      - /home/mbacalan/games/abioticfactor:/app/abioticfactor
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001" # Server/API
      - "25565:25565" # Minecraft Server
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-api.rule=Host(`home-api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard-api.entrypoints=websecure"
      - "traefik.http.routers.dashboard-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard-api.service=dashboard-api"
      - "traefik.http.services.dashboard-api.loadbalancer.server.port=3001"

      # Websocket config
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.dashboard-api.middlewares=websocket@docker"

      # Minecraft server
      - "traefik.http.routers.minecraft.rule=Host(`minecraft.${DOMAIN_NAME}`)"
      - "traefik.http.routers.minecraft.entrypoints=web"
      - "traefik.http.routers.minecraft.service=minecraft"
      - "traefik.http.services.minecraft.loadbalancer.server.port=25565"
