services:
  web:
    image: nginx:alpine
    container_name: dashboard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./dist/:/usr/share/nginx/dashboard:ro
      - /home/mbacalan/games/minecraft/plugins/Pl3xMap/web:/usr/share/nginx/mc-map:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
