services:
  web:
    image: nginx:alpine
    container_name: dashboard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./dist/:/usr/share/nginx/dashboard:ro
      - /home/mbacalan/games/minecraft/plugins/Pl3xMap/web:/usr/share/nginx/mc-map:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
  api:
    build: .
    container_name: dashboard-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/mbacalan/games/minecraft:/app/minecraft
    ports:
      - "3001:3001"
      - "25565:25565"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
